# fly.toml app configuration file generated for pokedex13 on 2023-07-07T09:27:43-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedex14"
primary_region = "sea"

[env]
  PORT = "8080" # add this

[experimental]
  auto_rollback = true

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.19.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
